
-- Upsert fine-grained categories
INSERT INTO "nanobanana_template_categories" (
  "id",
  "name",
  "icon",
  "color",
  "order_index",
  "is_active",
  "created_at",
  "updated_at"
) VALUES 
(
    'sci-fi',
    'Sci-Fi',
    'sparkles',
    '#0ea5e9',
    1,
    true,
    now(),
    now()
  ),
(
    '3d-art',
    '3D Art',
    'box',
    '#a855f7',
    2,
    true,
    now(),
    now()
  ),
(
    'design',
    'Design',
    'zap',
    '#f59e0b',
    3,
    true,
    now(),
    now()
  ),
(
    'photography',
    'Photography',
    'camera',
    '#22c55e',
    4,
    true,
    now(),
    now()
  ),
(
    'anime',
    'Anime',
    'sparkles',
    '#ef4444',
    5,
    true,
    now(),
    now()
  ),
(
    'artistic',
    'Artistic',
    'palette',
    '#eab308',
    6,
    true,
    now(),
    now()
  ),
(
    'manipulation',
    'Manipulation',
    'blend',
    '#06b6d4',
    7,
    true,
    now(),
    now()
  ),
(
    'utility',
    'Utility',
    'scissors',
    '#64748b',
    8,
    true,
    now(),
    now()
  ),
(
    'material',
    'Material',
    'layers',
    '#14b8a6',
    9,
    true,
    now(),
    now()
  ),
(
    'video',
    'Video',
    'film',
    '#8b5cf6',
    10,
    true,
    now(),
    now()
  )
ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "icon" = EXCLUDED."icon",
  "color" = EXCLUDED."color",
  "order_index" = EXCLUDED."order_index",
  "is_active" = EXCLUDED."is_active",
  "updated_at" = now();

-- Ensure target table has the required column when running seeds in mismatched environments
alter table if exists public.nanobanana_templates
  add column if not exists category_id text;

alter table if exists public.nanobanana_templates
  add column if not exists is_featured boolean default false;

alter table if exists public.nanobanana_templates
  add column if not exists is_premium boolean default false;

alter table if exists public.nanobanana_templates
  add column if not exists usage_count integer default 0;

alter table if exists public.nanobanana_templates
  add column if not exists rating numeric(2,1) default 0.0;

alter table if exists public.nanobanana_templates
  add column if not exists rating_count integer default 0;

alter table if exists public.nanobanana_templates
  add column if not exists author_name text;

alter table if exists public.nanobanana_templates
  add column if not exists difficulty_level text;

alter table if exists public.nanobanana_templates
  add column if not exists estimated_time integer;

alter table if exists public.nanobanana_templates
  add column if not exists tags text[];

alter table if exists public.nanobanana_templates
  add column if not exists description text;

alter table if exists public.nanobanana_templates
  add column if not exists parameters jsonb default '{}'::jsonb;

alter table if exists public.nanobanana_templates
  add column if not exists preview_images text[];

alter table if exists public.nanobanana_templates
  add column if not exists created_at timestamptz default now();

alter table if exists public.nanobanana_templates
  add column if not exists updated_at timestamptz default now();

drop index if exists public.idx_nanobanana_templates_name;

-- Upsert templates with category_id
INSERT INTO "nanobanana_templates" (
  "id",
  "name",
  "image_url",
  "prompt",
  "type",
  "description",
  "category_id",
  "isvalid",
  "is_featured",
  "usage_count",
  "rating",
  "rating_count",
  "difficulty_level",
  "estimated_time",
  "author_name",
  "tags",
  "created_at",
  "updated_at"
) VALUES 
(
      'tpl_local_001',
      'Creative Ad',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-Bt055iW47OUqRDOh-K0gZ.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      429,
      4.0,
      81,
      'intermediate',
      44,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_002',
      'Chrome Emoji Badge',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-ameZsuCqj7Px_1-NLwLhj.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'TEXT_TO_IMAGE',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      false,
      152,
      4.5,
      0,
      'beginner',
      51,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_003',
      'Monochrome Muse',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-pDsaB4o_oiNIjud_j5ypp.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'TEXT_TO_IMAGE',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      false,
      170,
      4.1,
      48,
      'advanced',
      12,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_004',
      'Clean Cutout',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-FpVTUFWK2dhd1GSysOFdh.png?v=1',
      'Remove background, isolate main subject on pure white. Clean edges, high-quality cutout.',
      'SINGLE_IMAGE_GENERATION',
      'Remove background, isolate main subject on pure white. Clean edges, high-quality cutout.',
      'utility',
      true,
      true,
      563,
      4.8,
      59,
      'intermediate',
      50,
      'NanoBanana',
      '{ai,creative,single_image_generation}',
      now(),
      now()
    ),
(
      'tpl_local_005',
      'Minimal Ad Layout',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-qVK6fm-fP8a4-LxpaN7Ji.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      748,
      4.5,
      79,
      'intermediate',
      53,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_006',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-eJzwap7e7KsSwJofY3ij8.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      942,
      4.3,
      49,
      'beginner',
      52,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_007',
      'Animal Landmark Selfie',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-yAd6PqQMt86VX6Nh1QFCl.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'TEXT_TO_IMAGE',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      true,
      477,
      4.9,
      24,
      'beginner',
      38,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_008',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-QCdSAN2IyigyHVVplpXGL.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'SINGLE_IMAGE_GENERATION',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      true,
      875,
      4.0,
      27,
      'beginner',
      13,
      'NanoBanana',
      '{ai,creative,single_image_generation}',
      now(),
      now()
    ),
(
      'tpl_local_009',
      'Out-of-Frame Perspective',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-ZwX4XJBz5BqMcvOXYcen0.png?v=1',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'SINGLE_IMAGE_GENERATION',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'photography',
      true,
      true,
      499,
      4.2,
      58,
      'advanced',
      37,
      'NanoBanana',
      '{ai,creative,single_image_generation}',
      now(),
      now()
    ),
(
      'tpl_local_010',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-jPX65pFLBMTvzVaCgSjlz.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      332,
      4.6,
      32,
      'beginner',
      29,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_011',
      'Isometric Keycaps',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-q-57zaITSb7d5Y21Ya6Rk.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      346,
      4.6,
      47,
      'beginner',
      60,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_012',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry--QWzIYAtO7KC3HthhsjH0.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      233,
      4.6,
      27,
      'intermediate',
      17,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_013',
      'Golden Hour Shot',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-vVoVQk6rVQBF2bGUMGfOr.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'TEXT_TO_IMAGE',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      false,
      376,
      4.9,
      53,
      'intermediate',
      34,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_014',
      'Letter Fusion',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-dk3V0sLLTD9fQW0DM9pxn.png?v=1',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'TEXT_TO_IMAGE',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'photography',
      true,
      false,
      617,
      5.0,
      8,
      'intermediate',
      55,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_015',
      'Silhouette',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-uWAtByJ544cdR5nBjMM3H.png?v=1',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'TEXT_TO_IMAGE',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'photography',
      true,
      false,
      357,
      4.9,
      33,
      'intermediate',
      41,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_016',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-nvAEqaxvslDn-p2hCKbHN.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      415,
      4.1,
      48,
      'intermediate',
      35,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_017',
      'Animal Landmark Selfie',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-NVse4zVhgYoKSGvN__y-m.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'TEXT_TO_IMAGE',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      false,
      859,
      4.1,
      14,
      'intermediate',
      41,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_018',
      'Logo Design',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-ukn_aztzA4yTNGNF1QCTl.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      true,
      425,
      4.1,
      11,
      'beginner',
      12,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_019',
      '3D Render',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-xl9zEu7r3VDXO_OZGM1a7.png?v=1',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      'TEXT_TO_IMAGE',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      '3d-art',
      true,
      false,
      308,
      4.6,
      82,
      'advanced',
      20,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_020',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-_aDii7pr31c7nBC30esLt.png?v=1',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      'TEXT_TO_IMAGE',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      '3d-art',
      true,
      false,
      0,
      4.4,
      71,
      'advanced',
      63,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_021',
      'Logo Design',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-Y5nxZct49r5jpDJgeziht.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      72,
      4.7,
      17,
      'advanced',
      12,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_022',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-Nc-vAhaIHqHisicziRUQ5.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      756,
      4.3,
      7,
      'beginner',
      30,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_023',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-jmGRjdDLKOu0Lwb-gg2Se.png?v=1',
      'retexture the image attached based on the json below:

{
  "style": "photorealistic",
  "material": "glass",
  "background": "plain white",
  "object_position": "centered",
  "lighting": "soft, diffused studio lighting",
  "camera_angle": "eye-level, straight-on",
  "resolution": "high",
  "aspect_ratio": "2:3",
  "details": {
    "reflections": true,
    "shadows": false,
    "transparency": true
  }
}',
      'TEXT_TO_IMAGE',
      'retexture the image attached based on the json below:

{
  "style": "photorealistic",
  "material": "glass",
  "background": "plain white",
  "object_position": "centered",
  "lighting": "soft, diffused studio lighting",
  "camera_angle": "eye-level, straight-on",
  "resolution": "high",
  "aspect_ratio": "2:3",
  "details": {
    "reflections": true,
    "shadows": false,
    "transparency": true
  }
}',
      'photography',
      true,
      false,
      664,
      4.1,
      72,
      'advanced',
      59,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_024',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-tcPJYJqWhSiLBt-KMnuyD.png?v=1',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      'TEXT_TO_IMAGE',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      '3d-art',
      true,
      false,
      706,
      4.8,
      53,
      'intermediate',
      13,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_025',
      '3D Render',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-8kfas56Jc3-f15O89pzKN.png?v=1',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      'TEXT_TO_IMAGE',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      '3d-art',
      true,
      true,
      314,
      4.4,
      9,
      'advanced',
      12,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_026',
      'Creative Ad',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-h3g_ajtU5hs70Yy0tskiN.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      662,
      4.9,
      57,
      'beginner',
      37,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_027',
      'Material Change',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-BOHwhmk-H-LxQ398epkPp.png?v=1',
      'Change material: shiny polished gold or rich oak wood. Realistic reflections and texture.',
      'SINGLE_IMAGE_GENERATION',
      'Change material: shiny polished gold or rich oak wood. Realistic reflections and texture.',
      'material',
      true,
      true,
      831,
      4.6,
      71,
      'advanced',
      45,
      'NanoBanana',
      '{ai,creative,single_image_generation}',
      now(),
      now()
    ),
(
      'tpl_local_028',
      'Cinematic Portrait',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-jyQlvtvYcyYWu61X_cWk6.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'TEXT_TO_IMAGE',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      true,
      703,
      4.5,
      15,
      'beginner',
      21,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_029',
      'Neon Nightscape',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-d4mtCy2DuZk2bkXiDMoOS.png?v=1',
      'Futuristic cyberpunk city at night with neon lights and wet streets. High detail, moody atmosphere.',
      'TEXT_TO_IMAGE',
      'Futuristic cyberpunk city at night with neon lights and wet streets. High detail, moody atmosphere.',
      'sci-fi',
      true,
      false,
      63,
      4.2,
      4,
      'advanced',
      60,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_030',
      'Chrome Emoji Badge',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-0fyYo7d2Vc3ufHnXU0fxh.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      169,
      4.6,
      53,
      'intermediate',
      19,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_031',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-WnFEERTJJbnDpcjKdb35U.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      610,
      4.1,
      88,
      'intermediate',
      46,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_032',
      'Logo Design',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-QGCQ1jjuNoKYgwFDo61qW.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      512,
      4.9,
      74,
      'beginner',
      43,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_033',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-rlprrmpgrWYxzcGFG6cN5.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      905,
      4.7,
      73,
      'beginner',
      11,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_034',
      'Monochrome Muse',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-sleMUJG0_smfYhUJ0x9zk.png?v=1',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'TEXT_TO_IMAGE',
      'High-contrast black-and-white portrait with soft gradient background and subtle film grain. Intimate mood, professional lighting.',
      'photography',
      true,
      true,
      320,
      4.8,
      58,
      'beginner',
      30,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_035',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-NwKHSkobGZuQuaTfzYnkk.png?v=1',
      'Change material: shiny polished gold or rich oak wood. Realistic reflections and texture.',
      'TEXT_TO_IMAGE',
      'Change material: shiny polished gold or rich oak wood. Realistic reflections and texture.',
      'material',
      true,
      false,
      887,
      4.4,
      63,
      'intermediate',
      6,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_036',
      '3D Render',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-ofHrVK4oclwpJayzpx6C5.png?v=1',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      'TEXT_TO_IMAGE',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      '3d-art',
      true,
      false,
      925,
      4.7,
      51,
      'beginner',
      9,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_037',
      'Chrome Emoji Badge',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-BZ4bE3tr5QKkaogEl_XQI.png?v=1',
      'Change material: shiny polished gold or rich oak wood. Realistic reflections and texture.',
      'TEXT_TO_IMAGE',
      'Change material: shiny polished gold or rich oak wood. Realistic reflections and texture.',
      'material',
      true,
      false,
      742,
      4.5,
      77,
      'advanced',
      40,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_038',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-5NAPAcMNSLl7j8PuX5mnt.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      564,
      4.1,
      19,
      'advanced',
      39,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_039',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-g1eDis0d0iaIEKLnkUSaa.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      949,
      4.6,
      98,
      'beginner',
      48,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_040',
      'Logo Design',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-4z8yN-EVHRBthTnpCB8Ka.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      706,
      4.4,
      43,
      'advanced',
      11,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_041',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-ufKQRU-0zXXlACt_A_DNd.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      915,
      4.2,
      20,
      'advanced',
      63,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_042',
      '3D Render',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-H0E8EqQ10jrbe0d8q7137.png?v=1',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      'TEXT_TO_IMAGE',
      'Cute 3D character in Pixar style, bright colors, studio lighting, high texture detail.',
      '3d-art',
      true,
      false,
      242,
      5.0,
      36,
      'intermediate',
      49,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_043',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-0bQpHIpimYLLrSJ8qe6C6.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      249,
      4.4,
      37,
      'intermediate',
      52,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_044',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-KMvfZkLFuvMEzCzBT8ywr.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      460,
      4.2,
      12,
      'beginner',
      52,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_045',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-REfe_PfgYfz67f5liafKu.png?v=1',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'TEXT_TO_IMAGE',
      'Artistic silhouette behind frosted glass. Crisp edge touches the surface; background soft grey gradient for a mysterious vibe.',
      'artistic',
      true,
      false,
      643,
      4.5,
      11,
      'intermediate',
      31,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_046',
      'Logo Design',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-0QNwJ8orXTqLGNNtoM2Uq.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      141,
      4.8,
      86,
      'advanced',
      49,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_047',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-SoZP2Zw1HCRXGONFdZSDs.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      388,
      4.9,
      72,
      'advanced',
      20,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_048',
      'Logo Design',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-uvbE1o3K9l86ZW1N1pNML.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      781,
      4.1,
      53,
      'beginner',
      33,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_049',
      'Fantasy Blend',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-retry-BLiip47sS1MZ2p6RoUSJN.png?v=1',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'TEXT_TO_IMAGE',
      'Seamlessly blend elements into a magical fantasy landscape with coherent lighting and glowing atmosphere.',
      'photography',
      true,
      false,
      825,
      4.7,
      46,
      'advanced',
      58,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    ),
(
      'tpl_local_050',
      'Iridescent Glass',
      'https://bibigpt-apps.chatvid.ai/chatimg/gemini-K-zMRlzu3y9bErJh5oDDe.png?v=1',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'TEXT_TO_IMAGE',
      'Minimal creative ad on white background. Real object + playful black ink doodles interact cleverly. Add bold black headline and brand logo.',
      'design',
      true,
      false,
      612,
      4.4,
      87,
      'beginner',
      10,
      'NanoBanana',
      '{ai,creative,text_to_image}',
      now(),
      now()
    )
ON CONFLICT ("id") 
DO UPDATE SET
  "image_url" = EXCLUDED."image_url",
  "prompt" = EXCLUDED."prompt",
  "type" = EXCLUDED."type",
  "description" = EXCLUDED."description",
  "category_id" = EXCLUDED."category_id",
  "updated_at" = now();

drop index if exists idx_nanobanana_templates_slug;
drop index if exists public.idx_nanobanana_templates_slug;

with cte as (
  select
    t.id,
    btrim(regexp_replace(regexp_replace(lower(t.name), '[^a-z0-9\s-]', '', 'g'), '[\s_-]+', '-', 'g'), '-') as base,
    replace(lower(t.id), '_','-') as id_slug,
    row_number() over (
      partition by btrim(regexp_replace(regexp_replace(lower(t.name), '[^a-z0-9\s-]', '', 'g'), '[\s_-]+', '-', 'g'), '-')
      order by t.id
    ) as rn
  from public.nanobanana_templates t
)
update public.nanobanana_templates as t
set slug = case
  when c.base = '' then c.id_slug
  when c.rn = 1 then c.base
  else c.base || '-' || right(c.id_slug, 6)
end
from cte c
where t.id = c.id;

create unique index if not exists idx_nanobanana_templates_slug on public.nanobanana_templates(slug);
